/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StatePlaygroundRouteImport } from './routes/state-playground'
import { Route as StateChallengeRouteImport } from './routes/state-challenge'
import { Route as EffectPlaygroundRouteImport } from './routes/effect-playground'
import { Route as EffectChallengeRouteImport } from './routes/effect-challenge'
import { Route as CompositionRouteImport } from './routes/composition'
import { Route as ComponentsPlaygroundRouteImport } from './routes/components-playground'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const StatePlaygroundRoute = StatePlaygroundRouteImport.update({
  id: '/state-playground',
  path: '/state-playground',
  getParentRoute: () => rootRouteImport,
} as any)
const StateChallengeRoute = StateChallengeRouteImport.update({
  id: '/state-challenge',
  path: '/state-challenge',
  getParentRoute: () => rootRouteImport,
} as any)
const EffectPlaygroundRoute = EffectPlaygroundRouteImport.update({
  id: '/effect-playground',
  path: '/effect-playground',
  getParentRoute: () => rootRouteImport,
} as any)
const EffectChallengeRoute = EffectChallengeRouteImport.update({
  id: '/effect-challenge',
  path: '/effect-challenge',
  getParentRoute: () => rootRouteImport,
} as any)
const CompositionRoute = CompositionRouteImport.update({
  id: '/composition',
  path: '/composition',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsPlaygroundRoute = ComponentsPlaygroundRouteImport.update({
  id: '/components-playground',
  path: '/components-playground',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/components-playground': typeof ComponentsPlaygroundRoute
  '/composition': typeof CompositionRoute
  '/effect-challenge': typeof EffectChallengeRoute
  '/effect-playground': typeof EffectPlaygroundRoute
  '/state-challenge': typeof StateChallengeRoute
  '/state-playground': typeof StatePlaygroundRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/components-playground': typeof ComponentsPlaygroundRoute
  '/composition': typeof CompositionRoute
  '/effect-challenge': typeof EffectChallengeRoute
  '/effect-playground': typeof EffectPlaygroundRoute
  '/state-challenge': typeof StateChallengeRoute
  '/state-playground': typeof StatePlaygroundRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/components-playground': typeof ComponentsPlaygroundRoute
  '/composition': typeof CompositionRoute
  '/effect-challenge': typeof EffectChallengeRoute
  '/effect-playground': typeof EffectPlaygroundRoute
  '/state-challenge': typeof StateChallengeRoute
  '/state-playground': typeof StatePlaygroundRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/components-playground'
    | '/composition'
    | '/effect-challenge'
    | '/effect-playground'
    | '/state-challenge'
    | '/state-playground'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/components-playground'
    | '/composition'
    | '/effect-challenge'
    | '/effect-playground'
    | '/state-challenge'
    | '/state-playground'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/components-playground'
    | '/composition'
    | '/effect-challenge'
    | '/effect-playground'
    | '/state-challenge'
    | '/state-playground'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ComponentsPlaygroundRoute: typeof ComponentsPlaygroundRoute
  CompositionRoute: typeof CompositionRoute
  EffectChallengeRoute: typeof EffectChallengeRoute
  EffectPlaygroundRoute: typeof EffectPlaygroundRoute
  StateChallengeRoute: typeof StateChallengeRoute
  StatePlaygroundRoute: typeof StatePlaygroundRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/state-playground': {
      id: '/state-playground'
      path: '/state-playground'
      fullPath: '/state-playground'
      preLoaderRoute: typeof StatePlaygroundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/state-challenge': {
      id: '/state-challenge'
      path: '/state-challenge'
      fullPath: '/state-challenge'
      preLoaderRoute: typeof StateChallengeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/effect-playground': {
      id: '/effect-playground'
      path: '/effect-playground'
      fullPath: '/effect-playground'
      preLoaderRoute: typeof EffectPlaygroundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/effect-challenge': {
      id: '/effect-challenge'
      path: '/effect-challenge'
      fullPath: '/effect-challenge'
      preLoaderRoute: typeof EffectChallengeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/composition': {
      id: '/composition'
      path: '/composition'
      fullPath: '/composition'
      preLoaderRoute: typeof CompositionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components-playground': {
      id: '/components-playground'
      path: '/components-playground'
      fullPath: '/components-playground'
      preLoaderRoute: typeof ComponentsPlaygroundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ComponentsPlaygroundRoute: ComponentsPlaygroundRoute,
  CompositionRoute: CompositionRoute,
  EffectChallengeRoute: EffectChallengeRoute,
  EffectPlaygroundRoute: EffectPlaygroundRoute,
  StateChallengeRoute: StateChallengeRoute,
  StatePlaygroundRoute: StatePlaygroundRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
